"""Kleine, offline nutzbare Graphenlabore mit nachvollziehbaren Koordinaten."""
import math,json
from html import escape as E
from mathtext import M, F
CONFIG={
 'power':dict(title='Aus einer Zahl wird ein Punkt',formula='f(x)=x²',xmin=-3,xmax=3,ymin=-1,ymax=10,x=2,step=.25,ask='Was passiert mit dem Funktionswert, wenn du x von 1 auf 2 verdoppelst?',answer='f(1)=1 und f(2)=4: Der Wert vervierfacht sich. Gleiche Abstände auf der x-Achse bedeuten bei einer Parabel keine gleichen Höhenunterschiede.',meaning='x ist die Eingabe, die Höhe y die Ausgabe. (2|4) bedeutet: Setze 2 ein, dann erhältst du 4. Beim Quadrat haben −2 und 2 denselben Funktionswert.',read='Vom gewählten x-Wert senkrecht bis zur Kurve gehen, dann waagerecht zur y-Achse: Dort steht f(x). Die gestrichelten Linien zeigen diesen Weg.'),
 'exponential':dict(title='Gleicher Faktor, immer größere Sprünge',formula='N(t)=2ᵗ',xmin=0,xmax=4,ymin=0,ymax=17,x=2,step=.25,ask='Sind die Zuwächse von t=0 auf 1 und von t=2 auf 3 gleich groß?',answer='Nein: 1→2 ist +1, 4→8 ist +4. Der Faktor ist in beiden Schritten 2. Deshalb wird die Kurve immer steiler.',meaning='Die Höhe steht für den Bestand. Ein Schritt nach rechts verdoppelt ihn. Die Zeit zum Verdoppeln bleibt gleich; der absolute Zuwachs wird größer.',read='Vergleiche Höhen im Abstand einer Zeiteinheit. Beim exponentiellen Wachstum bleibt ihr Verhältnis gleich, nicht ihre Differenz.'),
 'trig':dict(title='Eine Schwingung lesen',formula='f(x)=sin(x)',xmin=0,xmax=6.284,ymin=-1.5,ymax=1.5,x=1.571,step=.001,ask='Warum ist f(0) ungefähr gleich f(6,28), aber nicht jeder Punkt dazwischen null?',answer='6,28 liegt nahe bei 2π, also einer ganzen Periode. Dazwischen durchläuft die Kurve einen Hoch- und einen Tiefpunkt. Nach einer Periode wiederholt sich der gesamte Verlauf.',meaning='Die Höhe wechselt regelmäßig zwischen −1 und 1. Das beschreibt zum Beispiel eine idealisierte Schwingung. x wird hier im Bogenmaß gemessen.',read='Amplitude: Abstand von der Mittellinie 0 zum Hochpunkt. Periode: Abstand zweier gleichartiger Stellen einer vollständigen Wiederholung.'),
 'derivative':dict(title='Höhe ist nicht Steigung',formula='f(x)=x²; f′(x)=2x',xmin=-3,xmax=3,ymin=-3,ymax=10,x=1,step=.25,ask='Bei x=−1 liegt die Parabel über der Achse. Steigt sie dort trotzdem?',answer='Nein. f(−1)=1 beschreibt die Höhe. f′(−1)=−2 beschreibt das Fallen nach rechts. Ein positiver Funktionswert sagt nichts über das Vorzeichen der Steigung aus.',meaning='Die blaue Kurve zeigt Funktionswerte, die orange gestrichelte Gerade die Tangente am gewählten Punkt. Ihre Steigung beschreibt die momentane Änderung.',read='Gehe gedanklich nach rechts: Steigt die Tangente, ist f′ positiv; fällt sie, ist f′ negativ. Am Scheitel ist sie waagerecht.'),
 'cubic':dict(title='Hochpunkt, Tiefpunkt und Nullstelle unterscheiden',formula='f(x)=x³−3x',xmin=-2.3,xmax=2.3,ymin=-6,ymax=6,x=-1,step=.1,ask='Ist der Hochpunkt automatisch die höchste Stelle der gesamten Funktion?',answer='Nein. (−1|2) ist ein lokaler Hochpunkt: nur in seiner Nähe liegen die übrigen Punkte tiefer. Für große positive x wächst die Funktion unbeschränkt.',meaning='Ein Schnitt mit der x-Achse bedeutet f(x)=0. An einem Extrempunkt ändert die Kurve ihre Richtung; dort wechselt f′ das Vorzeichen.',read='Verfolge die Kurve von links nach rechts: steigend bis x=−1, fallend bis x=1, danach wieder steigend. Die Wendestelle bei x=0 ist kein Extremum.'),
 'integral':dict(title='Fläche als Bilanz lesen',formula='r(t)=t−1',xmin=0,xmax=3,ymin=-1.5,ymax=2.5,x=2,step=.1,ask='Bei der Grenze b=2 ist das Integral null. Ist deshalb nichts passiert?',answer='Nein. Von 0 bis 1 liegt ein negatives Dreieck mit Beitrag −1/2, von 1 bis 2 ein positives mit +1/2. Die Bilanz ist 0; die geometrische Fläche beträgt 1.',meaning='Blau schattierte Beiträge liegen oberhalb der Achse, orange unterhalb. Im Integral zählen sie mit Vorzeichen. Der Anfangsbestand ist darin noch nicht enthalten.',read='Nicht nur auf die Höhe schauen: Für einen Beitrag brauchst du Höhe × Zeitbreite. Rate in L/min mal Zeit in min ergibt einen Inhalt in L.'),
 'growth':dict(title='Steigend und trotzdem langsamer',formula='B(t)=8−6e^(−0,5t)',xmin=0,xmax=8,ymin=0,ymax=9,x=2,step=.25,ask='Wenn die Kurve flacher wird: Nimmt dann der Bestand ab?',answer='Nein. Er steigt weiterhin, weil die Steigung positiv bleibt. Lediglich die Zunahme wird kleiner. Der Bestand nähert sich 8 von unten.',meaning='Der Startbestand ist 2. Die gestrichelte waagerechte Linie bei 8 ist die Schranke. Sie wird für endliche Zeiten in diesem Modell nicht erreicht.',read='Kurvenhöhe = Bestand; Steigung = Änderungsrate. Eine flacher werdende Kurve kann weiterhin steigen.'),
 'inverse':dict(title='Eine Lücke ist keine Nullstelle',formula='f(x)=1/x',xmin=-4,xmax=4,ymin=-5,ymax=5,x=1,step=.25,ask='Die Kurve wechselt an x=0 die Seite der Achse. Ist x=0 eine Nullstelle?',answer='Nein. Bei x=0 ist der Term nicht definiert, weil man nicht durch 0 teilen darf. Keine der beiden Kurvenhälften schneidet die x-Achse.',meaning='Der Graph besteht aus zwei getrennten Ästen. Die Achsen sind Asymptoten: Der Graph nähert sich ihnen an, ohne sie zu schneiden.',read='Achte auf Lücken im Definitionsbereich. Über eine Lücke hinweg darfst du keine Verbindungslinie und keinen Zwischenwert annehmen.'),
 'parameter':dict(title='Ein Parameter verändert die ganze Kurve',formula='fₐ(x)=ax²+1',xmin=-3,xmax=3,ymin=-9,ymax=10,x=1,step=.25,ask='Welcher Punkt bleibt bei jedem Wert von a auf dem Graphen?',answer='(0|1), denn a·0²+1=1 für jedes a. Bei a=0 ist der Graph die waagerechte Gerade y=1; er ist dann keine Parabel.',meaning='x wählt einen Punkt auf der Kurve. a wählt die Kurve selbst. Positives a öffnet nach oben, negatives nach unten.',read='Ändere zuerst a und beobachte Form und Öffnung. Bewege dann x: Du liest einen Punkt auf genau dieser Kurve ab.'),
 'binomial':dict(title='Ein Balken ist eine Wahrscheinlichkeit',formula='X~B(6;0,5)',xmin=0,xmax=6,ymin=0,ymax=.4,x=3,step=1,ask='Bedeutet der höchste Balken bei k=3, dass immer genau drei Treffer auftreten?',answer='Nein. Genau drei Treffer sind das wahrscheinlichste einzelne Ergebnis, aber P(X=3)=20/64=0,3125. Auch andere Trefferzahlen können vorkommen.',meaning='Sechs unabhängige Versuche, jeweils Trefferchance 1/2. Die Höhe eines Balkens ist P(X=k). Die Summe aller sieben Balkenhöhen ist 1.',read='„Höchstens k“: Balkenhöhen von 0 bis k addieren. „Mindestens k“: Balkenhöhen von k bis 6 addieren. Bei diskreten Werten keine Verbindungskurve erfinden.'),
 'sequence':dict(title='Eine Folge besteht aus einzelnen Punkten',formula='aₙ=4·(1/2)ⁿ',xmin=0,xmax=6,ymin=0,ymax=4.5,x=2,step=1,ask='Erreicht die Folge irgendwann exakt den Wert 0?',answer='Nein. Für jedes endliche n bleibt 4·(1/2)ⁿ positiv. Die Werte kommen 0 beliebig nahe; 0 ist ihr Grenzwert.',meaning='n zählt ganze Schritte, beginnend bei 0. Deshalb stehen hier Punkte statt einer durchgehenden Linie. In jedem Schritt halbiert sich der Wert.',read='Lies zuerst die Startnummer: a₀=4. Ein Grenzwert beschreibt das langfristige Verhalten und muss kein tatsächlich vorkommendes Folgenglied sein.')
}
MAP={'10.1':'power','10.2':'exponential','10.4':'trig','E.1':'power','E.2':'derivative','E.3':'cubic','E.4':'exponential','E.5':'trig','E.6':'inverse','E.7':'sequence','Q1.1':'integral','Q1.2':'integral','Q1.3':'growth','Q1.5':'growth','Q2.1':'inverse','Q3.2':'binomial','Q3.3':'binomial','Q4.1':'parameter','Q4.2':'derivative','ABI.1':'cubic','ABI.3':'binomial','R.4':'exponential'}
def value(k,x,a=1):
    return {'power':lambda:x*x,'exponential':lambda:2**x,'trig':lambda:math.sin(x),'derivative':lambda:x*x,'cubic':lambda:x**3-3*x,'integral':lambda:x-1,'growth':lambda:8-6*math.exp(-.5*x),'inverse':lambda:1/x if abs(x)>1e-9 else None,'parameter':lambda:a*x*x+1,'binomial':lambda:math.comb(6,int(x))/64,'sequence':lambda:4*.5**x}[k]()
def graph(uid):
    if uid not in MAP:return ''
    k=MAP[uid];c=CONFIG[k];x=c['x'];y=value(k,x)
    X=lambda t:65+(t-c['xmin'])*510/(c['xmax']-c['xmin'])
    Y=lambda t:315-(t-c['ymin'])*270/(c['ymax']-c['ymin'])
    ticksx=list(range(math.ceil(c['xmin']),math.floor(c['xmax'])+1))
    dy=.1 if k=='binomial' else .5 if k in ('trig','integral') else 2 if c['ymax']>=9 else 1
    ticksy=[i*dy for i in range(math.ceil(c['ymin']/dy),math.floor(c['ymax']/dy)+1)]
    grid=''.join(f'<path d="M{X(v):.2f} 45V315"/><text x="{X(v):.2f}" y="340" text-anchor="middle">{v}</text>' for v in ticksx)
    grid+=''.join(f'<path d="M65 {Y(v):.2f}H575"/><text x="53" y="{Y(v)+5:.2f}" text-anchor="end">{v:g}</text>' for v in ticksy)
    paths='';points=[];prev=None
    if k in ('binomial','sequence'):
        for v in ticksx:
            yy=value(k,v)
            paths+=(f'<rect class="probability-bar" x="{X(v)-13:.2f}" y="{Y(yy):.2f}" width="26" height="{Y(0)-Y(yy):.2f}"/>' if k=='binomial' else f'<circle class="sequence-dot" cx="{X(v):.2f}" cy="{Y(yy):.2f}" r="5"/>')
    else:
        for i in range(501):
            xx=c['xmin']+(c['xmax']-c['xmin'])*i/500;yy=value(k,xx)
            if yy is None or (k=='inverse' and abs(xx)<.06):prev=None;continue
            points.append(f'{"M" if prev is None or (k=="inverse" and xx*prev<0) else "L"}{X(xx):.2f},{Y(yy):.2f}');prev=xx
        paths='<path class="lab-curve" d="'+' '.join(points)+'"/>'
    tangent=f'<path class="lab-tangent" d="M{X(c["xmin"])} {Y(2*x*c["xmin"]-x*x)}L{X(c["xmax"])} {Y(2*x*c["xmax"]-x*x)}"/>' if k=='derivative' else ''
    if k=='growth':tangent=f'<path class="lab-tangent" d="M65 {Y(8)}H575"/>'
    if k=='integral':
        paths=f'<path class="area-negative" d="M{X(0)} {Y(0)}L{X(0)} {Y(-1)}L{X(1)} {Y(0)}Z"/><path class="area-positive" d="M{X(1)} {Y(0)}L{X(2)} {Y(1)}L{X(2)} {Y(0)}Z"/>'+paths
    svg=f'''<svg viewBox="0 0 640 370" role="img" aria-labelledby="lab-title lab-desc"><title id="lab-title">{E(c['title'])}</title><desc id="lab-desc">{E(c['meaning'])}</desc><defs><clipPath id="lab-clip"><rect x="51" y="40" width="538" height="276"/></clipPath></defs><g class="lab-grid">{grid}</g><path class="lab-axes" d="M65 {Y(0)}H585 M{X(0)} 315V35"/><text x="590" y="{min(309,Y(0)+5)}">{'k' if k=='binomial' else 'n' if k=='sequence' else 't' if k in ('growth','integral','exponential') else 'x'}</text><text x="65" y="24">{'P(X=k)' if k=='binomial' else 'y'}</text><g clip-path="url(#lab-clip)">{paths}{tangent}<path class="lab-guide" d="M{X(x)} {Y(0)}V{Y(y)}H{X(0)}"/><circle class="lab-point" cx="{X(x)}" cy="{Y(y)}" r="6"/></g></svg>'''
    controls='<div class="lab-controls js-only">'
    if k=='parameter':controls+='<label>Kurve wählen: a <output data-a-output>1</output><input data-lab-a type="range" min="-2" max="2" step="0.25" value="1"></label>'
    controls+=f'<label>{"Trefferzahl k" if k=="binomial" else "Schritt n" if k=="sequence" else "Rechte Grenze b" if k=="integral" else "Punkt wählen: t" if k in ("exponential","growth") else "Punkt wählen: x"} <output data-x-output>{x:g}</output><input data-lab-x type="range" min="{c["xmin"] if k not in ("binomial","sequence") else 0}" max="{c["xmax"] if k!="trig" else 6.283}" step="{c["step"]}" value="{x}"></label><button type="button" data-lab-reset>Zurücksetzen</button></div>'
    config=dict(c,kind=k)
    return f'''<section class="graph-lab" aria-label="Graph verstehen" data-graph-lab='{E(json.dumps(config,ensure_ascii=False),quote=True)}'><span class="eyebrow">SEHEN · VERMUTEN · AUSPROBIEREN</span><h3>{E(c['title'])}</h3><p>{E(c['meaning'])}</p><div class="math-line lab-formula">{F(c['formula'])}</div>{svg}{controls}<output class="lab-reading" aria-live="polite" data-lab-reading>Punkt ({x:g} | {y:.3f}) – die gestrichelten Linien verbinden Eingabe und Ausgabe.</output><div class="reading-help"><strong>So liest du diesen Graphen</strong><p>{E(c['read'])}</p><p>Die Zahlen an den Achsen sind entscheidend: Ein Kästchen kann waagerecht und senkrecht unterschiedliche Werte darstellen. Ausschnitt und Skalierung verändern den optischen Eindruck.</p></div><details class="think-first"><summary>Erst überlegen: {E(c['ask'])}</summary><p>{M(c['answer'])}</p></details></section>'''
